excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length:
  - 10000 # warning
  - 10000 # error
disabled_rules:
  - trailing_whitespace
  - colon
  - force_cast